/* auto-generated by NAPI-RS */
/* eslint-disable */
/** An extracted frame. */
export interface JsExtractedFrame {
  /** Path to frame image */
  path: string
  /** Timestamp in seconds */
  timestampSeconds: number
  /** Frame number */
  frameNumber: number
  /** Is keyframe */
  isKeyframe: boolean
}

/** Frame with scene detection info. */
export interface JsFrameCandidate {
  /** Path to frame */
  path: string
  /** Timestamp */
  timestampSeconds: number
  /** Frame number */
  frameNumber: number
  /** Is keyframe */
  isKeyframe: boolean
  /** Hash as hex string */
  hashHex: string
  /** Is scene change */
  isSceneChange: boolean
  /** Is duplicate */
  isDuplicate: boolean
  /** Distance from previous */
  distanceFromPrevious: number
}

/** Pipeline config. */
export interface JsPipelineConfig {
  /** Video config */
  video?: JsVideoConfig
  /** Scene config */
  scene?: JsSceneConfig
  /** Transcription config */
  transcription?: JsTranscriptionConfig
  /** Enable scene detection */
  enableSceneDetection?: boolean
  /** Skip transcription */
  skipTranscription?: boolean
}

/** Processing statistics. */
export interface JsProcessingStats {
  /** Frames extracted */
  framesExtracted: number
  /** Scene changes detected */
  sceneChanges: number
  /** Duplicates found */
  duplicates: number
  /** Extraction time (ms) */
  extractionTimeMs: number
  /** Scene detection time (ms) */
  sceneDetectionTimeMs: number
  /** Transcription time (ms) */
  transcriptionTimeMs: number
}

/** Scene detection config. */
export interface JsSceneConfig {
  /** Hash size (8 or 16) */
  hashSize?: number
  /** Scene change threshold */
  sceneThreshold?: number
  /** Duplicate threshold */
  duplicateThreshold?: number
}

/** Transcription config. */
export interface JsTranscriptionConfig {
  /** Model path */
  modelPath?: string
  /** Language code */
  language?: string
  /** Thread count (0 = auto) */
  threads?: number
  /** Translate to English */
  translate?: boolean
}

/** Transcription result. */
export interface JsTranscriptionResult {
  /** Full text */
  text: string
  /** Segments */
  segments: Array<JsTranscriptSegment>
  /** Detected language */
  detectedLanguage?: string
  /** Duration in seconds */
  durationSeconds: number
}

/** Transcript segment. */
export interface JsTranscriptSegment {
  /** Start time (ms) */
  startMs: number
  /** End time (ms) */
  endMs: number
  /** Text */
  text: string
  /** Confidence (optional) */
  confidence?: number
}

/** Video extraction config. */
export interface JsVideoConfig {
  /** Output directory */
  outputDir?: string
  /** Max frames (0 = all) */
  maxFrames?: number
  /** Interval between frames (seconds) */
  intervalSeconds?: number
  /** Quality (1-31, lower is better) */
  quality?: number
  /** Output format: "jpeg" or "png" */
  format?: string
  /** Extract keyframes only */
  keyframesOnly?: boolean
}

/** Video metadata. */
export interface JsVideoMetadata {
  /** Duration in seconds */
  durationSeconds: number
  /** Frame rate */
  frameRate: number
  /** Total frames */
  frameCount: number
  /** Width in pixels */
  width: number
  /** Height in pixels */
  height: number
  /** Codec name */
  codec: string
  /** Has audio */
  hasAudio: boolean
}

/** Video processing output. */
export interface JsVideoProcessingOutput {
  /** Metadata */
  metadata: JsVideoMetadata
  /** Frames with scene info */
  frames: Array<JsFrameCandidate>
  /** Transcript (if available) */
  transcript?: JsTranscriptionResult
  /** No audio in video */
  noAudio: boolean
  /** Stats */
  stats: JsProcessingStats
}

/**
 * Check if `FFmpeg` is available.
 *
 * # Errors
 *
 * Returns `Ok(false)` if `FFmpeg` is not found; does not error.
 */
export declare function videoCheckFfmpeg(): Promise<boolean>

/**
 * Extract frames from a video.
 *
 * # Errors
 *
 * Returns an error if frame extraction fails.
 */
export declare function videoExtractFrames(videoPath: string, config?: JsVideoConfig | undefined | null): Promise<Array<JsExtractedFrame>>

/** Get the default model path. */
export declare function videoGetDefaultModelPath(): string

/**
 * Get video metadata.
 *
 * # Errors
 *
 * Returns an error if the video cannot be read or `FFmpeg` fails.
 */
export declare function videoGetMetadata(videoPath: string): Promise<JsVideoMetadata>

/** Get the download URL for the default Whisper model. */
export declare function videoGetModelUrl(): string

/** Check if Whisper model is available. */
export declare function videoIsModelAvailable(modelPath?: string | undefined | null): boolean

/**
 * Full video processing pipeline.
 *
 * # Errors
 *
 * Returns an error if any pipeline stage fails.
 */
export declare function videoProcess(videoPath: string, config?: JsPipelineConfig | undefined | null): Promise<JsVideoProcessingOutput>

/**
 * Transcribe audio from a video.
 *
 * # Errors
 *
 * Returns an error if transcription fails or the model is unavailable.
 */
export declare function videoTranscribe(videoPath: string, config?: JsTranscriptionConfig | undefined | null): Promise<JsTranscriptionResult>
