/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Compute decayed association strength.
 *
 * state: "fresh", "consolidating", "consolidated", "reconsolidating"
 */
export declare function computeAssociationDecay(initialStrength: number, daysSinceReinforced: number, state: string, config?: JsAssociationDecayConfig | undefined | null): number

/**
 * Compute base-level activation from access history.
 *
 * B(m) = ln[Σ(t_k)^(-d)]
 */
export declare function computeBaseLevel(accessTimesMs: Array<number>, currentTimeMs: number, decay: number): number

/**
 * Compute effective thresholds with boundary modulators.
 *
 * Returns `[effective_theta_low, effective_theta_high]`.
 */
export declare function computeEffectiveThresholds(thetaLow: number, thetaHigh: number, accessCount: number, daysSinceLastAccess: number, config?: JsReconsolidationConfig | undefined | null): Array<number>

/**
 * Compute encoding strength for a memory.
 *
 * Stronger encoding = more reliable retrieval.
 */
export declare function computeEncodingStrength(attention: number, emotionalWeight: number, accessCount: number, config?: JsInstanceNoiseConfig | undefined | null): number

/**
 * Compute per-memory noise parameter from encoding strength.
 *
 * Stronger encoding = lower noise.
 */
export declare function computeInstanceNoise(encodingStrength: number, noiseBase: number): number

/**
 * Compute session-aware decay rate based on recency.
 *
 * Returns decay rate in range [0.3, 0.5]:
 * - Last 30 min: 0.3
 * - Last 2 hours: 0.4
 * - Last 24 hours: 0.45
 * - Older: 0.5
 */
export declare function computeSessionDecayRate(lastAccessMs: number, currentTimeMs: number): number

/** Batch compute session-aware decay rates. */
export declare function computeSessionDecayRateBatch(lastAccessMs: Array<number>, currentTimeMs: number): Array<number>

/** Compute surprise (prediction error) between expected and actual. */
export declare function computeSurprise(expectedEmbedding: Array<number>, actualEmbedding: Array<number>, memoryAgeDays: number, memoryStrength: number, baseThreshold: number): number

/**
 * Compute working memory boost for a memory.
 *
 * Returns boost in range [1.0, 1.0 + `max_boost`].
 * Recently activated memories get higher boost.
 */
export declare function computeWorkingMemoryBoost(activatedAtMs: number, currentTimeMs: number, config?: JsWorkingMemoryConfig | undefined | null): number

/** Batch compute working memory boosts. */
export declare function computeWorkingMemoryBoostBatch(activatedAtMs: Array<number>, currentTimeMs: number, config?: JsWorkingMemoryConfig | undefined | null): Array<number>

/** Compute cosine similarity between two vectors. */
export declare function cosineSimilarity(a: Array<number>, b: Array<number>): number

/** Batch compute cosine similarity between probe and all memories. */
export declare function cosineSimilarityBatch(probe: Array<number>, memories: Array<Array<number>>): Array<number>

/** Create temporal links for an episode. */
export declare function createEpisodeLinks(eventMemoryIndices: Array<number>, config?: JsTemporalSpreadingConfig | undefined | null): Array<JsTemporalLink>

/**
 * Embed a single text. Returns { vector, model, dimensions }.
 *
 * # Errors
 *
 * Returns an error if the model is not loaded or embedding fails.
 */
export declare function embed(text: string): JsEmbeddingResult

/**
 * Embed a batch of texts.
 *
 * # Errors
 *
 * Returns an error if the model is not loaded or embedding fails.
 */
export declare function embedBatch(texts: Array<string>): Array<JsEmbeddingResult>

/**
 * Find temporally adjacent memories.
 *
 * direction: "before", "after", or "both"
 */
export declare function findTemporalNeighbors(temporalLinks: Array<JsTemporalLink>, anchorMemory: number, direction: string, limit: number): Array<JsTemporalNeighbor>

/** Check if model files exist at the given (or default) paths. */
export declare function isEmbeddingModelAvailable(modelPath?: string | undefined | null, tokenizerPath?: string | undefined | null): boolean

/** Check if the embedding model is currently loaded. */
export declare function isEmbeddingModelLoaded(): boolean

/** Result of activity type inference. */
export interface JsActivityInference {
  /** The inferred activity type (reading, writing, debugging, refactoring, reviewing, unknown) */
  activityType: string
  /** How it was inferred (explicit, keyword, tool, default) */
  source: string
  /** Confidence level (0-1) */
  confidence: number
}

/** Associated location result. */
export interface JsAssociatedLocation {
  /** Location index */
  locationId: number
  /** Association strength */
  strength: number
}

/** Association between two memories for spreading activation. */
export interface JsAssociation {
  source: number
  target: number
  forwardStrength: number
  backwardStrength: number
}

/** Configuration for association decay. */
export interface JsAssociationDecayConfig {
  /** Decay tau for fresh associations in days (default: 1/24 = 1 hour) */
  tauFreshDays?: number
  /** Decay tau for consolidating associations in days (default: 1) */
  tauConsolidatingDays?: number
  /** Decay tau for consolidated associations in days (default: 30) */
  tauConsolidatedDays?: number
  /** Decay tau for reconsolidating associations in days (default: 7) */
  tauReconsolidatingDays?: number
  /** Strength boost when co-accessed (default: 0.05) */
  reinforcementBoost?: number
  /** Prune threshold (default: 0.1) */
  pruneThreshold?: number
}

/** Embedding result returned to JavaScript. */
export interface JsEmbeddingResult {
  /** The embedding vector (768 dimensions). */
  vector: Array<number>
  /** Model name. */
  model: string
  /** Number of dimensions. */
  dimensions: number
}

/** Emotional context of a visual memory. */
export interface JsEmotionalContext {
  /** Pleasant (+1) to unpleasant (-1) */
  valence: number
  /** High activation (1) to low activation (0) */
  arousal: number
}

/** A candidate frame for description. */
export interface JsFrameCandidate {
  /** Frame index in the video */
  index: number
  /** Timestamp in seconds */
  timestampSeconds: number
  /** Whether this is a keyframe (I-frame) */
  isKeyframe: boolean
  /** Whether this is a scene change */
  isSceneChange: boolean
  /** Quality score (0-1) */
  qualityScore: number
}

/** Configuration for frame description prompts. */
export interface JsFrameDescriptionConfig {
  /** Whether to include emotional assessment */
  includeEmotion?: boolean
  /** Whether to detect and list objects */
  detectObjects?: boolean
  /** Maximum description length guidance */
  maxDescriptionLength?: number
}

/** Configuration for instance noise calculation. */
export interface JsInstanceNoiseConfig {
  /** Minimum encoding strength (default: 0.3) */
  encodingBase?: number
  /** Contribution from attention (default: 0.2) */
  attentionWeight?: number
  /** Contribution from emotion (default: 0.2) */
  emotionalWeight?: number
  /** Contribution from rehearsal (default: 0.3) */
  rehearsalWeight?: number
  /** Max rehearsal count before diminishing returns (default: 10) */
  maxRehearsalCount?: number
  /** Base noise parameter (default: 0.25) */
  noiseBase?: number
}

/** Association between two locations. */
export interface JsLocationAssociation {
  /** Source location index */
  source: number
  /** Target location index */
  target: number
  /** Association strength (0-1) */
  strength: number
  /** Number of co-accesses */
  coAccessCount: number
}

/** Configuration for location operations. */
export interface JsLocationConfig {
  /** Familiarity curve coefficient (default: 0.1) */
  familiarityK?: number
  /** Days before decay begins (default: 30) */
  staleThresholdDays?: number
  /** Maximum decay rate (default: 0.10) */
  maxDecayRate?: number
  /** How much familiarity reduces decay (default: 0.8) */
  decayDampening?: number
  /** Minimum familiarity floor (default: 0.1) */
  baseFloor?: number
  /** Extra floor for well-known locations (default: 0.4) */
  stickyBonus?: number
  /** Threshold for "well-known" (default: 0.7) */
  wellKnownThreshold?: number
  /** Multiplier: task + same activity (default: 5.0) */
  taskSameActivityMultiplier?: number
  /** Multiplier: task + different activity (default: 3.0) */
  taskDiffActivityMultiplier?: number
  /** Multiplier: time + same activity (default: 2.0) */
  timeSameActivityMultiplier?: number
  /** Multiplier: time + different activity (default: 1.0) */
  timeDiffActivityMultiplier?: number
  /** Backward strength factor (default: 0.7) */
  backwardStrengthFactor?: number
}

/** A location (file) with familiarity metrics. */
export interface JsLocationIntuition {
  /** Index in the location array */
  id: number
  /** Familiarity level (0-1) */
  familiarity: number
  /** Number of times accessed */
  accessCount: number
  /** Number of searches avoided */
  searchesSaved: number
  /** Last access timestamp (ms) */
  lastAccessedMs: number
  /** Whether pinned (immune to decay) */
  isPinned: boolean
}

/** Pruning candidate. */
export interface JsPruningCandidate {
  /** Memory index */
  index: number
  /** Current significance */
  significance: number
  /** Days since access */
  daysSinceAccess: number
  /** Reason: "lowsignificance", "stale", "duplicate", "lowquality" */
  reason: string
  /** Pruning score */
  score: number
}

/** Configuration for reconsolidation calculations. */
export interface JsReconsolidationConfig {
  /** Lower PE threshold (default: 0.10) */
  thetaLow?: number
  /** Upper PE threshold (default: 0.55) */
  thetaHigh?: number
  /** Sigmoid steepness (default: 10.0) */
  beta?: number
  /** How much encoding strength shifts `θ_high` down (default: 0.15) */
  strengthShift?: number
  /** How much memory age shifts `θ_low` up (default: 0.05) */
  ageShift?: number
  /** Baseline access count for normalization (default: 5.0) */
  baselineCount?: number
  /** Baseline days since access for normalization (default: 1.0) */
  baselineDays?: number
}

/** Result candidate from retrieval. */
export interface JsRetrievalCandidate {
  /** Memory index */
  index: number
  /** Base-level activation from access history */
  baseLevel: number
  /** Probe-trace activation (cubed similarity) */
  probeActivation: number
  /** Spreading activation from associated memories */
  spreading: number
  /** Emotional weight factor */
  emotionalWeight: number
  /** Combined total activation */
  totalActivation: number
  /** Retrieval probability (0-1) */
  probability: number
}

/** Configuration for retrieval. */
export interface JsRetrievalConfig {
  /** Decay rate for base-level activation (default: 0.5) */
  decayRate?: number
  /** Retrieval threshold (default: 0.3) */
  activationThreshold?: number
  /** Noise parameter (default: 0.1) */
  noiseParameter?: number
  /** Spreading activation depth (default: 3) */
  spreadingDepth?: number
  /** Spreading decay per hop (default: 0.7) */
  spreadingDecay?: number
  /** Minimum probability to include (default: 0.1) */
  minProbability?: number
  /** Maximum results to return (default: 10) */
  maxResults?: number
  /** Whether to spread bidirectionally (default: true) */
  bidirectional?: boolean
}

/** A temporal link between memories. */
export interface JsTemporalLink {
  sourcePosition: number
  targetPosition: number
  sourceMemory: number
  targetMemory: number
  forwardStrength: number
  backwardStrength: number
}

/** Temporal neighbor result. */
export interface JsTemporalNeighbor {
  memoryIndex: number
  strength: number
}

/** Configuration for temporal spreading. */
export interface JsTemporalSpreadingConfig {
  /** Forward link strength multiplier (default: 1.0) */
  forwardStrength?: number
  /** Backward link strength multiplier (default: 0.7) */
  backwardStrength?: number
  /** Distance decay rate (default: 0.3) */
  distanceDecayRate?: number
  /** Episode boost (default: 1.2) */
  episodeBoost?: number
  /** Context persistence (default: 0.7) */
  contextPersistence?: number
  /** Max temporal distance (default: 10) */
  maxTemporalDistance?: number
}

/** Result of temporal spreading. */
export interface JsTemporalSpreadingResult {
  activations: Array<number>
  forwardActivated: Array<number>
  backwardActivated: Array<number>
}

/** A transcript segment for context. */
export interface JsTranscriptSegment {
  /** Start timestamp in seconds */
  startSeconds: number
  /** End timestamp in seconds */
  endSeconds: number
  /** The transcribed text */
  text: string
}

/** Configuration for visual memory operations. */
export interface JsVisualConfig {
  /** Significance threshold for tagging (default: 0.6) */
  taggingSignificanceThreshold?: number
  /** Emotional retention threshold (default: 0.7) */
  emotionalRetentionThreshold?: number
  /** How much emotion reduces decay (default: 0.5) */
  emotionalDecayReduction?: number
  /** Base decay rate (default: 0.05) */
  baseDecayRate?: number
  /** Days before decay (default: 14) */
  staleThresholdDays?: number
  /** Significance floor (default: 0.1) */
  significanceFloor?: number
  /** Pruning threshold (default: 0.2) */
  pruningThreshold?: number
  /** Pruning stale days (default: 90) */
  pruningStaleDays?: number
  /** Preserve keyframes (default: true) */
  preserveKeyframes?: boolean
}

/** Consolidation state. */
export interface JsVisualConsolidationState {
  /** State: "fresh", "consolidating", "consolidated", "reconsolidating" */
  state: string
  /** Consolidation strength (0-1) */
  strength: number
  /** Reactivation count */
  reactivationCount: number
}

/** A visual memory with full metadata. */
export interface JsVisualMemory {
  /** Unique identifier */
  id: number
  /** Short description (the "gist") */
  description: string
  /** Detailed description (optional) */
  detailedDescription?: string
  /** When captured */
  capturedAtMs: number
  /** Last access timestamp */
  lastAccessedMs: number
  /** Access count */
  accessCount: number
  /** Emotional valence (-1 to 1) */
  emotionalValence: number
  /** Emotional arousal (0 to 1) */
  emotionalArousal: number
  /** Significance score (0-1) */
  significance: number
  /** Source type */
  source: string
  /** Who shared this */
  sharedBy?: string
  /** Video ID if frame */
  videoId?: string
  /** Frame number */
  frameNumber?: number
  /** Detected objects */
  objects: Array<string>
  /** Tags */
  tags: Array<string>
  /** Whether pinned */
  isPinned: boolean
}

/** Result from visual retrieval. */
export interface JsVisualRetrievalCandidate {
  /** Memory index */
  index: number
  /** Base-level activation */
  baseLevel: number
  /** Probe activation */
  probeActivation: number
  /** Spreading activation */
  spreading: number
  /** Emotional weight */
  emotionalWeight: number
  /** Significance boost applied */
  significanceBoost: number
  /** Total activation */
  totalActivation: number
  /** Retrieval probability */
  probability: number
}

/** Configuration for visual retrieval. */
export interface JsVisualRetrievalConfig {
  /** Decay rate (default: 0.5) */
  decayRate?: number
  /** Activation threshold (default: 0.3) */
  activationThreshold?: number
  /** Noise parameter (default: 0.1) */
  noiseParameter?: number
  /** Spreading depth (default: 3) */
  spreadingDepth?: number
  /** Spreading decay (default: 0.7) */
  spreadingDecay?: number
  /** Min probability (default: 0.1) */
  minProbability?: number
  /** Max results (default: 10) */
  maxResults?: number
  /** Bidirectional spreading (default: true) */
  bidirectional?: boolean
  /** Emotional boost (default: 0.3) */
  emotionalBoost?: number
  /** Significance boost (default: 0.2) */
  significanceBoost?: number
}

/** Where a visual memory originated. */
export interface JsVisualSource {
  /** Source type: "discord", "sms", "direct", "videoframe", "other" */
  sourceType: string
}

/** Configuration for working memory boost calculation. */
export interface JsWorkingMemoryConfig {
  /** Decay time constant in milliseconds (default: 4000) */
  decayMs?: number
  /** Maximum boost multiplier (default: 1.0, giving range [1.0, 2.0]) */
  maxBoost?: number
}

/**
 * Load the BGE-base-en-v1.5 embedding model from disk.
 *
 * Call this once at startup. Subsequent calls are no-ops.
 * Returns true if the model is loaded (or was already loaded).
 *
 * # Errors
 *
 * Returns an error if model files are missing or ONNX Runtime fails to load.
 */
export declare function loadEmbeddingModel(modelPath?: string | undefined | null, tokenizerPath?: string | undefined | null): boolean

/** Compute association strength with multiplier based on context. */
export declare function locationAssociationStrength(currentCount: number, isSameTask: boolean, isSameActivity: boolean, config?: JsLocationConfig | undefined | null): number

/**
 * Compute familiarity for a given access count.
 *
 * Uses asymptotic curve: f(n) = 1 - 1/(1 + k*n)
 */
export declare function locationComputeFamiliarity(accessCount: number, config?: JsLocationConfig | undefined | null): number

/** Get locations associated with a given location, sorted by strength. */
export declare function locationGetAssociated(locationId: number, associations: Array<JsLocationAssociation>, limit: number): Array<JsAssociatedLocation>

/**
 * Infer activity type from context string and optional tool name.
 *
 * Precedence: explicit > keyword > tool > default
 */
export declare function locationInferActivity(context: string, toolName?: string | undefined | null, explicitType?: string | undefined | null): JsActivityInference

/** Check if a location is well-known based on familiarity threshold. */
export declare function locationIsWellKnown(familiarity: number, config?: JsLocationConfig | undefined | null): boolean

/**
 * Apply nonlinear activation (MINERVA 2's cubic function).
 *
 * A(i) = S(i)³
 */
export declare function nonlinearActivation(similarity: number): number

/**
 * Determine prediction error zone.
 *
 * Returns `"reinforce"`, `"reconsolidate"`, or `"new_trace"`.
 */
export declare function peZone(peAbs: number, thetaLowEff: number, thetaHighEff: number): string

/**
 * Compute reconsolidation probability using dual-sigmoid bell curve.
 *
 * Returns probability of reconsolidation (peaks in the middle PE zone).
 */
export declare function reconsolidationProbability(peAbs: number, thetaLow: number, thetaHigh: number, beta: number): number

/** Reinforce an association (co-access boost). */
export declare function reinforceAssociation(currentStrength: number, config?: JsAssociationDecayConfig | undefined | null): number

/**
 * Compute retrieval probability using logistic function.
 *
 * P(retrieval) = 1 / (1 + e^((τ - A) / s))
 */
export declare function retrievalProbability(activation: number, threshold: number, noise: number): number

/**
 * Full retrieval pipeline using ACT-R spreading activation and MINERVA 2.
 *
 * This is the core retrieval function that combines:
 * 1. Probe-trace similarity (cosine similarity)
 * 2. Working Memory boost (applied to similarity before cubing)
 * 3. Nonlinear activation (MINERVA 2's cubic function)
 * 4. Base-level activation (recency/frequency from ACT-R)
 * 5. Spreading activation through association graph
 *
 * # Arguments
 *
 * * `probe_embedding` - The query embedding vector
 * * `memory_embeddings` - All memory embedding vectors (2D array)
 * * `access_histories_ms` - Access timestamps (ms) for each memory
 * * `emotional_weights` - Emotional weight (0-1) for each memory
 * * `decay_rates` - Decay rate for each memory (or use config default)
 * * `working_memory_boosts` - WM boost for each memory (1.0 = no boost, up to 2.0)
 * * `current_time_ms` - Current time in milliseconds
 * * `associations` - Optional association graph edges
 * * `config` - Optional retrieval configuration
 */
export declare function retrieve(probeEmbedding: Array<number>, memoryEmbeddings: Array<Array<number>>, accessHistoriesMs: Array<Array<number>>, emotionalWeights: Array<number>, decayRates: Array<number>, workingMemoryBoosts: Array<number>, currentTimeMs: number, associations?: Array<JsAssociation> | undefined | null, config?: JsRetrievalConfig | undefined | null): Array<JsRetrievalCandidate>

/** Check if an association should be pruned. */
export declare function shouldPruneAssociation(strength: number, config?: JsAssociationDecayConfig | undefined | null): boolean

/** Spread activation through temporal links. */
export declare function spreadTemporalActivation(numMemories: number, temporalLinks: Array<JsTemporalLink>, seedMemory: number, seedActivation: number, config?: JsTemporalSpreadingConfig | undefined | null): JsTemporalSpreadingResult

/** Library version */
export declare function version(): string

/**
 * Generate a prompt for Claude Haiku to describe a video frame.
 *
 * Returns a prompt string to send to Claude Haiku along with the image.
 */
export declare function videoPrepareForSubagent(timestampSeconds: number, videoDurationSeconds: number, transcriptNearFrame: string | undefined | null, isSceneChange: boolean, sharedBy?: string | undefined | null, config?: JsFrameDescriptionConfig | undefined | null): string

/** Generate a synthesis prompt for combining frame descriptions. */
export declare function videoPrepareSynthesisPrompt(descriptions: Array<string>, valences: Array<number>, arousals: Array<number>, significances: Array<number>, timestamps: Array<number>, transcript: string | undefined | null, videoDurationSeconds: number): string

/**
 * Select frames for description, respecting rate limits.
 *
 * Prioritizes: keyframes, scene changes, even distribution, transcript moments.
 *
 * # Returns
 *
 * Indices of selected frames in chronological order.
 */
export declare function videoSelectFrames(frames: Array<JsFrameCandidate>, maxFrames: number, transcriptSegments?: Array<JsTranscriptSegment> | undefined | null): Array<number>

/** Retrieve visual memories based on probe embedding. */
export declare function visualRetrieve(probeEmbedding: Array<number>, memoryEmbeddings: Array<Array<number>>, accessHistoriesMs: Array<Array<number>>, emotionalWeights: Array<number>, significanceScores: Array<number>, currentTimeMs: number, associations?: Array<JsAssociation> | undefined | null, config?: JsVisualRetrievalConfig | undefined | null): Array<JsVisualRetrievalCandidate>

/** Check if a visual memory should be pruned. */
export declare function visualShouldPrune(significance: number, daysSinceAccess: number, isPinned: boolean, isKeyframe: boolean, config?: JsVisualConfig | undefined | null): boolean
