/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Compute base-level activation from access history.
 *
 * B(m) = ln[Σ(t_k)^(-d)]
 */
export declare function computeBaseLevel(accessTimesMs: Array<number>, currentTimeMs: number, decay: number): number

/** Compute surprise (prediction error) between expected and actual. */
export declare function computeSurprise(expectedEmbedding: Array<number>, actualEmbedding: Array<number>, memoryAgeDays: number, memoryStrength: number, baseThreshold: number): number

/** Compute cosine similarity between two vectors. */
export declare function cosineSimilarity(a: Array<number>, b: Array<number>): number

/** Batch compute cosine similarity between probe and all memories. */
export declare function cosineSimilarityBatch(probe: Array<number>, memories: Array<Array<number>>): Array<number>

/** Association between two memories for spreading activation. */
export interface JsAssociation {
  source: number
  target: number
  forwardStrength: number
  backwardStrength: number
}

/** Result candidate from retrieval. */
export interface JsRetrievalCandidate {
  /** Memory index */
  index: number
  /** Base-level activation from access history */
  baseLevel: number
  /** Probe-trace activation (cubed similarity) */
  probeActivation: number
  /** Spreading activation from associated memories */
  spreading: number
  /** Emotional weight factor */
  emotionalWeight: number
  /** Combined total activation */
  totalActivation: number
  /** Retrieval probability (0-1) */
  probability: number
  /** Estimated retrieval latency (ms) */
  latencyMs: number
}

/** Configuration for retrieval. */
export interface JsRetrievalConfig {
  /** Decay rate for base-level activation (default: 0.5) */
  decayRate?: number
  /** Retrieval threshold (default: 0.3) */
  activationThreshold?: number
  /** Noise parameter (default: 0.1) */
  noiseParameter?: number
  /** Spreading activation depth (default: 3) */
  spreadingDepth?: number
  /** Spreading decay per hop (default: 0.7) */
  spreadingDecay?: number
  /** Minimum probability to include (default: 0.1) */
  minProbability?: number
  /** Maximum results to return (default: 10) */
  maxResults?: number
  /** Whether to spread bidirectionally (default: true) */
  bidirectional?: boolean
}

/**
 * Apply nonlinear activation (MINERVA 2's cubic function).
 *
 * A(i) = S(i)³
 */
export declare function nonlinearActivation(similarity: number): number

/**
 * Compute retrieval probability using logistic function.
 *
 * P(retrieval) = 1 / (1 + e^((τ - A) / s))
 */
export declare function retrievalProbability(activation: number, threshold: number, noise: number): number

/**
 * Full retrieval pipeline using ACT-R spreading activation and MINERVA 2.
 *
 * This is the core retrieval function that combines:
 * 1. Probe-trace similarity (cosine similarity)
 * 2. Nonlinear activation (MINERVA 2's cubic function)
 * 3. Base-level activation (recency/frequency from ACT-R)
 * 4. Spreading activation through association graph
 *
 * # Arguments
 *
 * * `probe_embedding` - The query embedding vector
 * * `memory_embeddings` - All memory embedding vectors (2D array)
 * * `access_histories_ms` - Access timestamps (ms) for each memory
 * * `emotional_weights` - Emotional weight (0-1) for each memory
 * * `decay_rates` - Decay rate for each memory (or use config default)
 * * `current_time_ms` - Current time in milliseconds
 * * `associations` - Optional association graph edges
 * * `config` - Optional retrieval configuration
 */
export declare function retrieve(probeEmbedding: Array<number>, memoryEmbeddings: Array<Array<number>>, accessHistoriesMs: Array<Array<number>>, emotionalWeights: Array<number>, decayRates: Array<number>, currentTimeMs: number, associations?: Array<JsAssociation> | undefined | null, config?: JsRetrievalConfig | undefined | null): Array<JsRetrievalCandidate>

/** Library version */
export declare function version(): string
